import { defineConfig } from 'vite';
import type { Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { fileURLToPath } from 'node:url';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

// SINGLEFILE=1 builds one self-contained index.html openable via file:// (see
// scripts/inline.mjs). It stubs the WASM/worker-based AI libs, which can't run
// from file://. The default build keeps them code-split for the hosted site.
const singlefile = process.env.SINGLEFILE === '1';
const stub = fileURLToPath(new URL('./src/lib/models/_stub_ml.ts', import.meta.url));

/**
 * Generates an offline service worker into the build so the app loads even when the serving port is
 * down (a reload / new tab is served from the SW cache). NOT for the single-file build (file:// has
 * no server + no SW). Precaches the app shell + code + styling + icons; source maps, wasm and the
 * heavy opt-in AI weights are left to be runtime-cached / handled by the app's own Cache-API stores.
 *
 * It only ever deletes its OWN stale precaches (the `hnlens-precache-*` prefix) on activate, so the
 * app's downloaded model-weight caches (managed separately by src/lib/models/storage.ts) survive.
 */
function offlineServiceWorker(): Plugin {
  let outDir = 'dist';
  return {
    name: 'hnlens-offline-sw',
    apply: 'build',
    configResolved(cfg) {
      outDir = cfg.build.outDir;
    },
    closeBundle() {
      if (singlefile) return;
      const files: string[] = [];
      const walk = (dir: string) => {
        for (const name of readdirSync(dir)) {
          const p = join(dir, name);
          if (statSync(p).isDirectory()) walk(p);
          else files.push(p);
        }
      };
      walk(outDir);
      const assets = files
        .map((p) => relative(outDir, p).split(/[\\/]/).join('/'))
        .filter((rel) => /\.(html|js|css|svg|png|ico|json|webmanifest|woff2?)$/.test(rel))
        .filter((rel) => !rel.endsWith('.map') && rel !== 'sw.js')
        .sort();
      const version = createHash('sha256').update(assets.join('\n')).digest('hex').slice(0, 12);
      const sw = `/* Auto-generated by vite.config.ts (offlineServiceWorker) — do not edit. */
const PRECACHE = 'hnlens-precache-${version}';
const RUNTIME = 'hnlens-runtime';
const SHELL = 'index.html';
const ASSETS = ${JSON.stringify(assets)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(PRECACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('hnlens-precache-') && k !== PRECACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Cross-origin (HN API, Algolia, model CDN, favicons) -> straight to network; the app caches its
  // own data in IndexedDB / its own Cache-API stores.
  if (url.origin !== self.location.origin) return;
  // SPA navigations -> the cached app shell, with a network fallback (works with the server down).
  if (req.mode === 'navigate') {
    e.respondWith(caches.match(SHELL).then((r) => r || fetch(req).catch(() => caches.match(SHELL))));
    return;
  }
  // Same-origin assets: cache-first, then network (runtime-caching lazy chunks / wasm on first use).
  e.respondWith(
    caches.match(req).then((cached) =>
      cached ||
      fetch(req).then((resp) => {
        if (resp && resp.ok && resp.type === 'basic') {
          const clone = resp.clone();
          caches.open(RUNTIME).then((c) => c.put(req, clone));
        }
        return resp;
      }).catch(() => caches.match(req))
    )
  );
});
`;
      writeFileSync(join(outDir, 'sw.js'), sw);
      // eslint-disable-next-line no-console
      console.log(`[hnlens-offline-sw] wrote ${outDir}/sw.js (${assets.length} precached assets, ${version})`);
    },
  };
}

export default defineConfig({
  base: './',
  plugins: [react(), tailwindcss(), ...(singlefile ? [] : [offlineServiceWorker()])],
  resolve: {
    alias: singlefile
      ? {
          '@huggingface/transformers': stub,
          '@mlc-ai/web-llm': stub,
        }
      : {},
  },
  build: {
    target: 'esnext', // web-llm / transformers.js use top-level await + wasm
    ...(singlefile
      ? {
          cssCodeSplit: false,
          assetsInlineLimit: 100_000_000,
          rollupOptions: { output: { inlineDynamicImports: true } },
        }
      : {}),
  },
  optimizeDeps: {
    // Heavy ML deps are loaded lazily via dynamic import; don't prebundle them.
    exclude: ['@huggingface/transformers', '@mlc-ai/web-llm'],
  },
});
