/**
 * Generate THIRD_PARTY_NOTICES.md from the RUNTIME dependencies in package.json.
 *
 * Why this exists: HN Lens ships as a static bundle, so every `dependencies` entry is redistributed
 * to users. Four of them are Apache-2.0, whose section 4(d) requires propagating any upstream NOTICE
 * file, and dompurify is dual-licensed so the elected license has to be stated. That is a real (if
 * small) legal obligation and it was previously undocumented.
 *
 * Generated rather than hand-written so it cannot drift from package.json — a hand-maintained
 * attribution list is exactly the kind of file that silently goes stale after a dependency bump.
 * `devDependencies` are deliberately excluded: they are build-time only and are not redistributed
 * (axe-core's MPL-2.0, for instance, never reaches a user).
 *
 * Usage: node scripts/gen-notices.mjs [--check]
 *   --check exits non-zero if the committed file is out of date, for CI/verify.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'THIRD_PARTY_NOTICES.md';
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const deps = Object.keys(pkg.dependencies ?? {}).sort();

/** Upstream NOTICE text, if the package ships one (Apache-2.0 §4(d)). */
function noticeFor(dir) {
  for (const n of ['NOTICE', 'NOTICE.txt', 'NOTICE.md']) {
    const p = join(dir, n);
    if (existsSync(p)) return readFileSync(p, 'utf8').trim();
  }
  return null;
}

const rows = [];
const notices = [];
for (const name of deps) {
  const dir = join('node_modules', name);
  if (!existsSync(join(dir, 'package.json'))) {
    console.error(`WARN: ${name} not installed — run npm ci first`);
    continue;
  }
  const m = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const license = m.license ?? (Array.isArray(m.licenses) ? m.licenses.map((l) => l.type).join(' OR ') : 'UNKNOWN');
  const home = m.homepage ?? m.repository?.url?.replace(/^git\+/, '').replace(/\.git$/, '') ?? '';
  rows.push({ name, version: m.version, license, home });
  const notice = noticeFor(dir);
  if (notice) notices.push({ name, notice });
}

const apache = rows.filter((r) => /Apache-2\.0/.test(r.license));
const lines = [];
lines.push('# Third-party notices');
lines.push('');
lines.push('HN Lens is MIT-licensed (see `LICENSE`). It is distributed as a static browser bundle, so');
lines.push('the runtime dependencies below are redistributed with it. This file lists them, their');
lines.push('licenses, and any upstream NOTICE text they require.');
lines.push('');
lines.push('Build-time-only packages (`devDependencies`) are not listed: they are not part of the');
lines.push('shipped bundle and are not redistributed.');
lines.push('');
lines.push('> Generated by `node scripts/gen-notices.mjs` — do not edit by hand.');
lines.push('');
lines.push('## Bundled runtime dependencies');
lines.push('');
lines.push('| Package | Version | License |');
lines.push('| --- | --- | --- |');
for (const r of rows) {
  const label = r.home ? `[${r.name}](${r.home})` : r.name;
  lines.push(`| ${label} | ${r.version} | ${r.license} |`);
}
lines.push('');
if (apache.length) {
  lines.push('## Apache License 2.0');
  lines.push('');
  lines.push(`The following are licensed under the Apache License, Version 2.0:`);
  lines.push('');
  for (const r of apache) lines.push(`- ${r.name} ${r.version}`);
  lines.push('');
  lines.push('You may obtain a copy of the license at <https://www.apache.org/licenses/LICENSE-2.0>.');
  lines.push('Unless required by applicable law or agreed to in writing, software distributed under');
  lines.push('the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY');
  lines.push('KIND, either express or implied.');
  lines.push('');
}
const dual = rows.filter((r) => /OR/.test(r.license));
if (dual.length) {
  lines.push('## Dual-licensed packages');
  lines.push('');
  for (const r of dual) {
    lines.push(`- **${r.name}** ${r.version} — offered as \`${r.license}\`. HN Lens elects the`);
    lines.push('  **Apache-2.0** option, so its terms are covered by the section above.');
  }
  lines.push('');
}
if (notices.length) {
  lines.push('## Upstream NOTICE files');
  lines.push('');
  lines.push('Reproduced as required by Apache-2.0 section 4(d).');
  lines.push('');
  for (const n of notices) {
    lines.push(`### ${n.name}`);
    lines.push('');
    lines.push('```text');
    lines.push(n.notice);
    lines.push('```');
    lines.push('');
  }
}
const out = lines.join('\n').replace(/\n{3,}/g, '\n\n');

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current.trim() !== out.trim()) {
    console.error(`${OUT} is out of date — run: node scripts/gen-notices.mjs`);
    process.exit(1);
  }
  console.log(`${OUT} is up to date (${rows.length} runtime deps, ${apache.length} Apache-2.0).`);
} else {
  writeFileSync(OUT, out + '\n');
  console.log(`wrote ${OUT} — ${rows.length} runtime deps, ${apache.length} Apache-2.0, ${notices.length} upstream NOTICE file(s).`);
}
